[package]
name = "b28xx"
version = "0.1.0"
authors = ["TheFel0x <43345523+TheFel0x@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
